mysite_T21/mysite_tut/urls.py
# Imports
from django.contrib import admin
from django.urls import include, path

# URL path declaration
urlpatterns = [
    path('', include("user_auth.urls")),
    path('polls/', include('polls.urls')), 
    path('admins/', admin.site.urls),
    path('user_auth/', include("django.contrib.auth.urls")),
    #path('user_auth/', include("user_auth.urls")),    
]

mysite_T21/polls/urls.py
# Import
from django.urls import path
from . import views

# namespacing 
app_name = 'polls'

# URL path declaration
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite_T21/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_reg, name='user_reg'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
    name='authenticate_user'),
    path('user/', views.show_user, name = 'show_user'),]

mysite_T21/polls/models.py
# imports
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    '''Question layout in database, method to determine recently published questions and string return for text'''
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    '''Choice layout in database and string return for text'''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite_T21/user_auth/models.py
from django.db import models

# Create your models here.

mysite_T21/polls/views.py
# Imports
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, path 
from django.views import generic
from django.utils import timezone
from .models import Choice, Question
from django.conf import settings
from django.shortcuts import redirect

class IndexView(generic.ListView):
    '''link template file index.html to view'''
    
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    '''link template file detail.html to detail view for question model'''
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    '''link template file results.html to view'''
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    '''Vote view
        - checks if user is logged in to vote
        - redirected to login screen if they are not logged in
        - if logged in they are able to vote
        - Admin is a regarded as logged in user and will need to log out each session
        '''
    if request.user.is_authenticated:
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    else: 
        return HttpResponseRedirect(reverse('user_auth:login') )   
        

        

mysite_T21/user_auth/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import redirect
from django.contrib.auth.models import User



@csrf_protect
def user_login(request):
    return render(request, 'user_auth/login.html')

def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:register')
)
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )    

def show_user(request):
    print(request.user.username)
    return render(request, 'user_auth/user.html', {
        "username": request.user.username,
        "password": request.user.password
    })   

def user_reg(request):
    return render(request, 'user_auth/register.html')

def register(request):
    username = request.GET['username']
    password = request.GET['password']
    user = User.objects.create_user(username, None, password)
    login(request, user)
    return HttpResponseRedirect(
            reverse('user_auth:show_user')
        )
    
    
	         

mysite_T21/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
<input type="submit" value="Vote">
</form>

mysite_T21/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite_T21/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite_T21/polls/templates/user_auth/login.html
<h1> Login as User </h1>
<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Login" />
</form>

mysite_T21/polls/templates/user_auth/register.html
<h1> Register as New User </h1>
<form action="{% url 'user_auth:register' %}" >
    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>
    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    <input type="submit" value="Register" />    
</form>
<form action="{% url 'user_auth:login' %}">
    <input type="submit" value="Already Registered? Login" />
</form>

mysite_T21/polls/templates/user_auth/user.html
<h1> Welcome, {{username}} </h1>
<p> Your password is {{password}}</p>